# Generated by Django 6.0.1 on 2026-06-23 03:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='service_type',
            field=models.CharField(blank=True, choices=[('home', 'Home Solar'), ('business', 'Business Solar'), ('industrial', 'Industrial Solar'), ('lighting', 'Solar Lighting'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=100),
        ),
    ]
